### DISCUSSION TITLE
Please provide css to make one line title only compact view of items

### DISCUSSION THREAD

**Discussion by bbrother92** [k-ivan/visual-bookmarks-chrome#110] [Ideas]
Could you please help, I want to make compact titles only view for bookmarks instead of cards

**Comment by k-ivan** [comment]
Hello @bbrother92!

Could you describe in more detail, because bookmarks are cards. Please specify where you want to compact  titles, do you mean folders?

**Reply by bbrother92** [reply]
Well I just want to arrage a lot of bookmarks in columns viewing them as a link with title without card picture (It takes up a lot of space).
Something similar to this https://lh3.googleusercontent.com/HmTwJ5jzub2TCMzepgcT6hp29r1JWVuBO3b--IyExVH-tuVFBhCLvqjC6J_42ppSXmH2Ggs-BvYnBoVBWCMhltAd=w640-h400-e365-rj-sc0x00ffffff

**Comment by k-ivan** [comment]
This view is not provided, but you can try with your own CSS styles.

approximately
![image](https://user-images.githubusercontent.com/6150895/211364023-6368473e-4f61-4b7e-a37f-4135c18da4e8.png)
```css
.grid {
  grid-auto-rows: 30px;
}
.bookmark__action,
.bookmark__img,
.bookmark__summary-folder {
  display: none;
}
.bookmark__caption {
  flex-grow: 1;
}
```
