### DISCUSSION TITLE
Settings - View - Number of Columns

### DISCUSSION THREAD

**Discussion by carloscperes** [k-ivan/visual-bookmarks-chrome#151] [Ideas]
How about enable different number of columns depending on the orientation or the width size the user chooses?
E.g.:
Portraint Orientation Number of Columns: 4
Landscape Orientation Number of Columns: 8
Max Width: 768 - Number of Columns: 4
Max Width: 1366 - Number of Columns: 8

This extension is amazing! Congrats.

**Comment by k-ivan** [comment]
Thank you, glad you like it!

Currently, the number of columns is calculated based on the width of the container specified in the settings. This option is convenient because it automatically scales, and this will not lead to breaking the layout.

Would you mind if I offer you a custom option with additional styles? You can override some styles you don't like.

Example for the screen sizes you described:
```css
@media (width < 1366px) {
  .grid {
    grid-auto-rows: unset;
  }
  .bookmark {
    aspect-ratio: 4 / 3;
  }
      
}
@media (width < 768px) {
  .grid {
    grid-template-columns: repeat(auto-fit, minmax(calc(100% / 5), 1fr));
  }
}
@media (768px < width < 1366px) {
  .grid {
    grid-template-columns: repeat(auto-fit, minmax(calc(100% / 10), 1fr));
  }
}
```
Enter the code above in the settings, as in the screenshot, you can play with all the values to get the state you need.
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/cddc084c-21a4-4aa4-91d0-3f5b05703477)
