### ISSUE TITLE
Request: an option to add space between thumbnails

### ISSUE THREAD

**Issue by dr3141** [k-ivan/visual-bookmarks-chrome#137]
Hi @k-ivan ,

this is a great extension, thanks for making it! 

Would you consider adding an option for adding a space between thumbnails? Just to allow for moving the thumbs away from each other - maybe a slider of some sort to let us choose the size? 

![Screenshot](https://github.com/k-ivan/visual-bookmarks-chrome/assets/134611316/a102515f-40ef-4614-bf89-88c91308ec69)

This is so we can go from this:
![1](https://github.com/k-ivan/visual-bookmarks-chrome/assets/134611316/7acdc071-2a0b-4ee2-9292-3b7571b97763)

to this:

![2](https://github.com/k-ivan/visual-bookmarks-chrome/assets/134611316/a1d99721-81f0-417f-bc42-cb3af4f90dd1)

Edit: screenshots added

Thanks

**Comment by k-ivan** [comment]
Hi @dr3141 

How about tuning custom `css`  maybe this is what you are looking for?
```css
:root {
  --grid-gap: 30px;
}
```

![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/986d77fc-7569-4e6d-a412-43cce29003ea)

**Comment by dr3141** [comment]
Holy crap man, that's exactly it! Love it, thanks.

Do you have something similarly simple and clever to change the colour of the bookmarks and the background? White bookmarks and grey background is what I'm looking for.

**Comment by k-ivan** [comment]
If I understand correctly, you can
```css
:root {
  --theme-background: gray;
  --bookmark-bg: white;
  --bookmark-caption-bg: white;
  --grid-gap: 30px;
}
.bookmark__title {
  font-size: 16px;
}```

**Comment by dr3141** [comment]
This is great, thanks a lot!

One last question - where does the extension save all the thumbnails on my PC? I'd like to change some of the thumbnails to greyscale by hand.

**Comment by k-ivan** [comment]
Unfortunately, getting and editing images will be very difficult. But you can use `css` again 😄 and use the css property filter.

For example:
```css
:root {
  --theme-background: gray;
  --bookmark-bg: white;
  --bookmark-caption-bg: white;
  --grid-gap: 30px;
}
.bookmark__title {
  font-size: 16px;
}
.bookmark__img {
    filter: grayscale(0.5);  /*you can play with a value from 0 to 1 */
}
```

**Comment by dr3141** [comment]
You are a magician! Thanks.

Since this css stuff is so useful, is there also a way to change the shape of the bookmarks to rectangular and add rounded corners to them?

**Comment by k-ivan** [comment]
The bookmarks already have round corners, but you can make them more visible. You need to change the variable `--bookmark-radius`

```css
:root {
  --theme-background: gray;
  --bookmark-bg: white;
  --bookmark-caption-bg: white;
  --grid-gap: 30px;
  --bookmark-radius: 14px;
}
.bookmark__title {
  font-size: 16px;
}
.bookmark__img {
    filter: grayscale(0.5);  /*you can play with a value from 0 to 1 */
}
```
