### ISSUE TITLE
[feature request] site icon improvement

### ISSUE THREAD

**Issue by Meonthb** [k-ivan/visual-bookmarks-chrome#161]
Can you add an option to change the site icon display like Safari? just remove the grey border and confine the site icon in a rounded rectangle, which I think more decent and easier to adjust.
![the way Safari deal with site icon](https://github.com/k-ivan/visual-bookmarks-chrome/assets/60881723/6df7251d-eb98-4de9-b3a1-1fd7956757fc)

**Comment by k-ivan** [comment]
Hello @Meonthb!

It won’t be possible to repeat it exactly, due to the fact that the grid is different, but perhaps this option will suit you.
Сopy the styles below and try to apply them
```css
.bookmark:has(.bookmark__img--logo) {
  --bookmark-bg: transparent;
  --bookmark-caption-bg: transparent;

  & .bookmark__favicon {
     display: none;
   }
  & .bookmark__caption {
     white-space: normal;
     height: auto;
     display: -webkit-box;
     -webkit-line-clamp: 3;
     -webkit-box-orient: vertical;  
     overflow: hidden;
   }
}

.bookmark__img--logo {
  flex-grow: 0;
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  margin: auto;
  background-color: beige;
  border-radius: var(--base-radius);
}
```
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/3ac37d70-e997-462f-a666-8db8c7f97979)

This example
![image](https://github.com/k-ivan/visual-bookmarks-chrome/assets/6150895/703086a5-cb88-431c-8b11-3875054b7dfa)
