### ISSUE TITLE
Подвинуть чуть

### ISSUE THREAD

**Issue by tipodanet** [k-ivan/visual-bookmarks-chrome#185]
![image](https://github.com/user-attachments/assets/7836a0f9-f20e-4bb0-84cb-0b0d27c55764)

**Comment by k-ivan** [comment]
Вы можете подвинуть с помощью собственных стилей

```css
.progress-toast {
  left: 5px;
  top: 5px;
}
```
