### ISSUE TITLE
thumbnail image just shown partially

### ISSUE THREAD

**Issue by MichaelLehner69** [k-ivan/visual-bookmarks-chrome#68]
is it possible to display the whole width of the website in the thumbnail? in my case the preview is shown, starting from the right border and important content at the left side of the screen is hidden. thx

**Comment by k-ivan** [comment]
Hello @MichaelLehner69 !

You can try using your own styles and `contain` value.

```css
.bookmark__img {
    background-size: contain;
}
```

But, in this case, the thumbnail will not be cropped, but you will have dark stripes around the edges.

**Comment by MichaelLehner69** [comment]
thanks, great. that worked as you said and i have grey stripes at the bottom. is there a way to get these black?

**Comment by k-ivan** [comment]
It looks like you have a light theme turned on, change it to dark in the settings and the background will be dark.

If you just need a light theme and dark stripes, then you can override this in the styles
example color #222
```css
.bookmark__img {
    background-color: #222; 
    background-size: contain;
}
```
